# Generated by Django 3.0 on 2023-02-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='blinkingLights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinput',
            name='msg',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userinput',
            name='offLights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinput',
            name='onLights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='serialNum',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
